#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

PKGSRC_VERSION='2015Q3'

# Exit if any commands fail
set -o errexit

echo "* Use the skylime pkgsrc mirror"
echo "http://pkgsrc.smartos.skylime.net/packages/SmartOS/${PKGSRC_VERSION}/x86_64/All" > /opt/local/etc/pkgin/repositories.conf
pkg_admin rebuild
pkgin -y up

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
