#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# add default fileserv users:
groupadd -g 1000 fileserv
useradd -g 1000 -d /tmp -s /usr/bin/false fileserv
useradd -g 1000 -d /tmp -s /usr/bin/false arthur
useradd -g 1000 -d /tmp -s /usr/bin/false gees

# Clean up
echo "* Cleaning up."
rm -rf /root/*
pkgin clean

# Prepare image for provisioning
sm-prepare-image -y
