#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# add users for kbrs
/usr/sbin/groupadd -g 5092 dsapid
/usr/sbin/useradd -u 5092 -g dsapid -d /opt/dsapid -s /usr/bin/bash dsapid

# Clean up
echo "* Cleaning up."
rm -rf /root/*
pkgin clean

# Prepare image for provisioning
sm-prepare-image -y
